### ISSUE TITLE
Issues with OPrint 0.15

### ISSUE THREAD

**Issue by tteggelit** [agrif/OctoPrint-InfluxDB#1]
I upgraded to OPrint 0.15 and things don't seem to work anymore. The first issue I got was 

```
2019-02-21 23:50:35,778 - octoprint.plugin - ERROR - Error while calling plugin influxdb
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/__init__.py", line 230, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_influxdb/__init__.py", line 177, in on_event
    self.influx_emit('events', {'type': event}, extra_tags=tags)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_influxdb/__init__.py", line 120, in influx_emit
   'measurement': self.influx_prefix + measurement,
AttributeError: 'InfluxDBPlugin' object has no attribute 'influx_prefix'
```
but that was easily fixed by adding:

`self.influx_prefix = ''` to `__init__`

Now I get:

```
2019-02-22 14:47:13,561 - octoprint.plugins.influxdb - INFO - connecting: database='octoprint', host='192.168.86.101', port=8086, ssl=False, use_udp=False
2019-02-22 14:47:13,563 - octoprint.plugins.influxdb - ERROR - Cannot connect to InfluxDB server.
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_influxdb/__init__.py", line 60, in influx_try_connect
    db = influxdb.InfluxDBClient(**kwargs)
AttributeError: 'module' object has no attribute 'InfluxDBClient'
```

However, everything seems to checkout. The path looks right:

```
2019-02-22 14:47:13,557 - octoprint.plugins.influxdb - INFO - sys.path: ['/home/pi/oprint/bin', '/home/pi/oprint/lib/python2.7', '/home/pi/oprint/lib/python2.7/plat-arm-linux-gnueabihf', '/home/pi/oprint/lib/python2.7/lib-tk', '/home/pi/oprint/lib/python2.7/lib-old', '/home/pi/oprint/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-arm-linux-gnueabihf', '/usr/lib/python2.7/lib-tk', '/home/pi/oprint/local/lib/python2.7/site-packages', '/home/pi/oprint/lib/python2.7/site-packages']
```

And manually trying things seems to work fine:

```
pi@octopi:~ $ oprint/bin/python2.7 
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import influxdb
>>> dir(influxdb)
['DataFrameClient', 'InfluxDBClient', 'SeriesHelper', '__all__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__', 'absolute_import', 'client', 'dataframe_client', 'division', 'exceptions', 'helper', 'line_protocol', 'print_function', 'resultset', 'unicode_literals']
>>> db=influxdb.InfluxDBClient(database='octoprint', host='192.168.86.101', port=8086, ssl=False, use_udp=False)
>>> db.ping()
'v1.5.2'
>>> import sys
>>> print(sys.path)
['', '/home/pi/oprint/lib/python2.7', '/home/pi/oprint/lib/python2.7/plat-arm-linux-gnueabihf', '/home/pi/oprint/lib/python2.7/lib-tk', '/home/pi/oprint/lib/python2.7/lib-old', '/home/pi/oprint/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-arm-linux-gnueabihf', '/usr/lib/python2.7/lib-tk', '/home/pi/oprint/local/lib/python2.7/site-packages', '/home/pi/oprint/lib/python2.7/site-packages']
```
I'm at a loss, any ideas what might be going on?

**Comment by tteggelit** [comment]
So I upgraded influxdb from 5.2.1 to 5.2.2 and that may have fixed the problem. At least it's no longer erroring out on boot.

**Comment by agrif** [comment]
Ack! Sorry I didn't notice this until now, my notifications have been broken for months.

OctoPi 0.15 runs a version of OctoPrint with a [bug that sounds a lot like what you've encountered](https://github.com/foosel/OctoPrint/pull/2978). It was fixed in OctoPrint 1.3.11. Can you verify if you are running OctoPrint 1.3.11 or later?

Other than that, I'm not sure what's going on.

**Comment by tteggelit** [comment]
I'm now running OctoPrint 1.3.11 now. Does that mean my earlier change of:

`self.influx_prefix = ''` to `__init__`

is also not needed?

**Comment by agrif** [comment]
It shouldn't be needed -- I'm running the plugin on 1.3.11 just fine.

If you change it back and it stops working, I'd like to hear about it.

**Comment by tteggelit** [comment]
I backed out the changed and restarted the OctoPrint server and didn't see any tracebacks, so it may be all good now. Thanks!
